Tickets: HallArr Class Reference
HallArr Class Reference
Клас който дефинира списък от зали
#include <HallArr.h>
Public Member Functions
HallArr ()
int getSize () const
const std::vector< Hall > & getHalls () const
HallArr & addHall (Hall &newHall)
adds a hall in the hall array
Hall * getHallByID (int id)
returns a hall by given id
Private Member Functions
void copy (const HallArr &other)
Private Attributes
std::vector< Hall > halls
Detailed Description
Клас който дефинира списък от зали
Definition at line 14 of file HallArr.h.
Constructor & Destructor Documentation
HallArr()
HallArr::HallArr ()
Definition at line 8 of file HallArr.cpp.
                  {
 }
Member Function Documentation
addHall()
HallArr & HallArr::addHall (Hall & newHall)
adds a hall in the hall array
Definition at line 27 of file HallArr.cpp.
{
     newHall.setId(this->getSize());
     this->halls.push_back(newHall);
     return *this;
 }
References getSize(), halls, and Hall::setId().
copy()
void HallArr::copy (const HallArr & other) private
Definition at line 12 of file HallArr.cpp.
{
     for (int i = 0; i < other.getSize(); i++) {
         this->halls[i] = other.halls[i];
     }
 }
References getSize(), and halls.
getHallByID()
Hall * HallArr::getHallByID (int id)
returns a hall by given id
Definition at line 34 of file HallArr.cpp.
{
     for(int i=0;i<this->getSize();i++){
         if(this->halls[i].getId() == id){
             return &this->halls[i];
         }
     }
     throw std::invalid_argument("not found");
 }
References getSize(), and halls.
getHalls()
const std::vector< Hall > & HallArr::getHalls () const
Definition at line 22 of file HallArr.cpp.
{
     return this->halls;
 }
References halls.
getSize()
int HallArr::getSize () const
Definition at line 18 of file HallArr.cpp.
{
     return this->getHalls().size();
 }
References getHalls().
Member Data Documentation
halls
std::vector<Hall> HallArr::halls private
Definition at line 16 of file HallArr.h.
The documentation for this class was generated from the following files:
C:/Users/Moni/CLionProjects/Tickets/headers/HallArr.h
C:/Users/Moni/CLionProjects/Tickets/sources/HallArr.cpp