Tickets: EventArr Class Reference
EventArr Class Reference
Клас който дефинира списък от събития
#include <EventArr.h>
Public Member Functions
EventArr ()
EventArr (const EventArr &other)
EventArr & operator= (const EventArr &other)
~EventArr ()
EventArr & addEvent (const Event &newEvent)
adds a event in the event array
int getSize () const
bool existsEventOnThisDay (const Event &event)
returns true if an event already exists on a given date
const std::vector< Event > & getEvents () const
Event * getEventByNameAndDate (const Date &date, const std::string &name)
returns a event by given date and name
Event * getEventByDateAndHall (const Date &date, const Hall &hall)
return an event by given date and hall
void getBookedTicketsOnDateWithName (const Date &date, const std::string &name)
prints booked tickets by given name and date
int getNumberOfBookedTickets (const Event &e)
returns the number of booked tickets by given event
void getBookedTicketsOnDate (const Date &date)
prints booked tickets by given date
void getBookedTicketsOnName (const std::string &name)
prints booked tickets by given name
void printMostPopularEvents ()
prints the most popular events by sorting them
Private Member Functions
void destroy ()
void copy (const EventArr &other)
Private Attributes
std::vector< Event > events
Detailed Description
Клас който дефинира списък от събития
Definition at line 15 of file EventArr.h.
Constructor & Destructor Documentation
EventArr() [1/2]
EventArr::EventArr ()
Definition at line 21 of file EventArr.cpp.
                    {
 }
EventArr() [2/2]
EventArr::EventArr (const EventArr & other)
Definition at line 24 of file EventArr.cpp.
{
     this->copy(other);
 }
References copy().
~EventArr()
EventArr::~EventArr ()
Definition at line 34 of file EventArr.cpp.
                     {
     this->destroy();
 }
References destroy().
Member Function Documentation
addEvent()
EventArr & EventArr::addEvent (const Event & newEvent)
adds a event in the event array
Definition at line 39 of file EventArr.cpp.
{
     if(existsEventOnThisDay(newEvent))
         throw std::invalid_argument( "received invalid date" );
     this->events.push_back(newEvent);
     return *this;
 }
References events, and existsEventOnThisDay().
copy()
void EventArr::copy (const EventArr & other) private
Definition at line 15 of file EventArr.cpp.
{
     for (int i = 0; i < other.getSize(); i++) {
         this->events[i] = other.events[i];
     }
 }
References events, and getSize().
destroy()
void EventArr::destroy () private
Definition at line 11 of file EventArr.cpp.
{
     delete this;
 }
existsEventOnThisDay()
bool EventArr::existsEventOnThisDay (const Event & event)
returns true if an event already exists on a given date
Definition at line 47 of file EventArr.cpp.
{
     for(int i=0;i<this->getSize();i++){
         Event e = this->events[i];
         if(e.getDay() == event.getDay()
         && e.getYear() == event.getYear()
         && e.getMonth() == event.getMonth()){
             return true;
         }
     }
     return false;
 }
References events, Event::getDay(), Event::getMonth(), getSize(), and Event::getYear().
getBookedTicketsOnDate()
void EventArr::getBookedTicketsOnDate (const Date & date)
prints booked tickets by given date
Definition at line 128 of file EventArr.cpp.
{
     int day = date.getDay();
     int month = date.getMonth();
     int year = date.getYear();
     for(int i=0;i<this->getSize();i++){
         Event event = this->getEvents()[i];
         if(event.getDay() == day
            && event.getMonth() == month
            && event.getYear() == year){
             std::cout<<"Booked tickets: "<<std::endl;
             int hallRows = event.getHall().getRows();
             int hallSeats = event.getHall().getSeats();
             for (int j = 1; j <= hallRows; j++) {
                 for(int z=1;z<=hallSeats;z++){
                     int seatToBook = ((j -1) * event.getHall().getSeats()) + (z-1);
                     if(event.getSeats()[seatToBook] == 0){
                         std::cout<<"["<<j<<","<<z<<"]"<<std::endl;
                     }
                 }
             }
             return;
         }
     }
 }
References Date::getDay(), getEvents(), Date::getMonth(), getSize(), and Date::getYear().
getBookedTicketsOnDateWithName()
void EventArr::getBookedTicketsOnDateWithName (const Date & date, const std::string & name)
prints booked tickets by given name and date
Definition at line 93 of file EventArr.cpp.
{
     for(int i=0;i<this->getSize();i++){
      Event event = this->getEvents()[i];
      if(date == event.getDate()
      && event.getName() == name){
          std::cout<<"Booked tickets: "<<std::endl;
          int hallRows = event.getHall().getRows();
          int hallSeats = event.getHall().getSeats();
          for (int j = 1; j <= hallRows; j++) {
             for(int z=1;z<=hallSeats;z++){
                 int seatToBook = ((j -1) * event.getHall().getSeats()) + (z-1);
                 if(event.getSeats()[seatToBook] == 0){
                     std::cout<<"["<<j<<","<<z<<"]"<<std::endl;
                 }
             }
          }
          return;
      }
     }
     throw std::invalid_argument("Nothing found!");
 }
References getEvents(), and getSize().
getBookedTicketsOnName()
void EventArr::getBookedTicketsOnName (const std::string & name)
prints booked tickets by given name
Definition at line 155 of file EventArr.cpp.
{
     for(int i=0;i<this->getSize();i++){
         Event event = this->getEvents()[i];
         if(event.getName() == name){
             std::cout<<"Booked tickets: "<<std::endl;
             int hallRows = event.getHall().getRows();
             int hallSeats = event.getHall().getSeats();
             for (int j = 1; j <= hallRows; j++) {
                 for(int z=1;z<=hallSeats;z++){
                     int seatToBook = ((j -1) * event.getHall().getSeats()) + (z-1);
                     if(event.getSeats()[seatToBook] == 0){
                         std::cout<<"["<<j<<","<<z<<"]"<<std::endl;
                     }
                 }
             }
             return;
         }
     }
 }
References getEvents(), and getSize().
getEventByDateAndHall()
Event * EventArr::getEventByDateAndHall (const Date & date, const Hall & hall)
return an event by given date and hall
Definition at line 82 of file EventArr.cpp.
{
     for(int i=0;i< this->getSize();i++){
         Event e = this->getEvents()[i];
         if(sameDate(date.getDay(),date.getMonth(),date.getYear(),e) && (e.getHall()==hall)){
             return &this->events[i];
         }
     }
     return nullptr;
 }
References events, Date::getDay(), getEvents(), Event::getHall(), Date::getMonth(), getSize(), Date::getYear(), and sameDate().
getEventByNameAndDate()
Event * EventArr::getEventByNameAndDate (const Date & date, const std::string & name)
returns a event by given date and name
Definition at line 71 of file EventArr.cpp.
{
     for(int i=0;i< this->getSize();i++){
         Event e = this->getEvents()[i];
         if(sameDate(date.getDay(),date.getMonth(),date.getYear(),e) && e.getName()==name){
             return &this->events[i];
         }
     }
     throw std::invalid_argument("Event not found!");
 }
References events, Date::getDay(), getEvents(), Date::getMonth(), Event::getName(), getSize(), Date::getYear(), and sameDate().
getEvents()
const std::vector< Event > & EventArr::getEvents () const
Definition at line 59 of file EventArr.cpp.
{
     return events;
 }
References events.
getNumberOfBookedTickets()
int EventArr::getNumberOfBookedTickets (const Event & e)
returns the number of booked tickets by given event
Definition at line 116 of file EventArr.cpp.
{
     int counter =0;
     for(int i : e.getSeats()){
         if(i == 0){
             counter++;
         }
     }
     return counter;
 }
References Event::getSeats().
getSize()
int EventArr::getSize () const
Definition at line 7 of file EventArr.cpp.
{
     return this->events.size();
 }
References events.
operator=()
EventArr & EventArr::operator= (const EventArr & other)
Definition at line 27 of file EventArr.cpp.
{
     if (this != &other) {
         this->destroy();
         this->copy(other);
     }
     return *this;
 }
References copy(), and destroy().
printMostPopularEvents()
void EventArr::printMostPopularEvents ()
prints the most popular events by sorting them
Definition at line 176 of file EventArr.cpp.
{
     std::map<Event , int> map;
     for(int i=0;i<this->getSize();i++){
         Event event = this->getEvents()[i];
         map[event] = event.getBoughtTicketsCount();
     }
     for (const auto& entry : map) {
         std::cout << "Event with name: " << entry.first.getName() << " has sold: " <<entry.second<<" tickets!"<< std::endl;
     }
 }
References getEvents(), and getSize().
Member Data Documentation
events
std::vector<Event> EventArr::events private
Definition at line 17 of file EventArr.h.
The documentation for this class was generated from the following files:
C:/Users/Moni/CLionProjects/Tickets/headers/EventArr.h
C:/Users/Moni/CLionProjects/Tickets/sources/EventArr.cpp