Tickets: Event Class Reference
Event Class Reference
Клас който дефинира събитие
#include <Event.h>
Public Member Functions
Event ()
Event (const std::string &name, const Hall &hall, const Date &date)
const std::string & getName () const
void setName (const std::string &name)
int getDay () const
int getMonth () const
int getYear () const
const std::vector< int > & getSeats () const
const Hall getHall () const
void setHall (Hall hall)
void bookTicket (int row, int seat, const std::string &note)
books a ticket on given row and seat and if adds a note if exist
void unbookTicket (int row, int seat)
unbooks a note on given row and seat
void buyTicket (int row, int seat)
buys a ticket on given row and seat
int getBoughtTicketsCount () const
return the number of tickets bought
bool operator< (const Event &other) const
const Date & getDate () const
void setDate (const Date &date)
Private Attributes
std::string name
Date date
Hall hall
std::vector< int > seats
std::map< std::pair< int, int >, std::string > notes
Detailed Description
Клас който дефинира събитие
Definition at line 17 of file Event.h.
Constructor & Destructor Documentation
Event() [1/2]
Event::Event ()
базов конструктор
Definition at line 24 of file Event.cpp.
              {
     int seatsCount = (this->getHall().getSeats() * this->getHall().getRows());
     for (int i = 0; i < seatsCount; i++) {
         this->seats.push_back(-1);
     }
 }
References getHall(), Hall::getRows(), Hall::getSeats(), and seats.
Event() [2/2]
Event::Event (const std::string & name, const Hall & hall, const Date & date)
конструктор с аргументи
Definition at line 32 of file Event.cpp.
{
     int seatsCount = ((hall.getRows() ) * (hall.getSeats()));
     for (int i = 0; i < seatsCount; i++) {
         this->seats.push_back(-1);
     }
     this->setName(name);
     this->setHall(hall);
     this->setDate(date);
 }
References Hall::getRows(), Hall::getSeats(), hall, seats, setDate(), setHall(), and setName().
Member Function Documentation
bookTicket()
void Event::bookTicket (int row, int seat, const std::string & note)
books a ticket on given row and seat and if adds a note if exist
метод за запазване на билет
Definition at line 60 of file Event.cpp.
{
     Hall h = this->getHall();
     int seatToBook = ((row -1) * h.getSeats()) + (seat-1);
     this->seats[seatToBook] = 0;
     this->notes.insert(std::pair<std::pair<int, int>, std::string>(std::make_pair(row, seat), note));
 }
References getHall(), Hall::getSeats(), notes, and seats.
buyTicket()
void Event::buyTicket (int row, int seat)
buys a ticket on given row and seat
метод за закупуване на билет
Definition at line 77 of file Event.cpp.
{
     Hall h = this->getHall();
     int seatToUnBook = ((row -1) * h.getSeats()) + (seat-1);
     this->seats[seatToUnBook] =1;
 }
References getHall(), Hall::getSeats(), and seats.
getBoughtTicketsCount()
int Event::getBoughtTicketsCount () const
return the number of tickets bought
метод който връща броя на закупените билети
Definition at line 83 of file Event.cpp.
{
     int counter =0;
     for(int i=0;i<this->getSeats().size();i++){
         if(this->getSeats()[i] == 1){
             counter++;
         }
     }
     return counter;
 }
References getSeats().
getDate()
const Date & Event::getDate () const
геттър на датата
Definition at line 97 of file Event.cpp.
{
     return date;
 }
References date.
getDay()
int Event::getDay () const
връща деня на събитието
Definition at line 42 of file Event.cpp.
{
     return this->date.getDay();
 }
References date, and Date::getDay().
getHall()
const Hall Event::getHall () const
връща залата на събитието
Definition at line 16 of file Event.cpp.
{
     return this->hall;
 }
References hall.
getMonth()
int Event::getMonth () const
връща месеца на събитието
Definition at line 46 of file Event.cpp.
{
     return this->date.getMonth();
 }
References date, and Date::getMonth().
getName()
const std::string & Event::getName () const
геттър на името
Definition at line 7 of file Event.cpp.
{
     return name;
 }
References name.
getSeats()
const std::vector< int > & Event::getSeats () const
връща местата на събитието
Definition at line 55 of file Event.cpp.
{
     return seats;
 }
References seats.
getYear()
int Event::getYear () const
връща годината на събитието
Definition at line 51 of file Event.cpp.
{
     return this->date.getYear();
 }
References date, and Date::getYear().
operator<()
bool Event::operator< (const Event & other) const
Definition at line 93 of file Event.cpp.
{
     return getBoughtTicketsCount()> other.getBoughtTicketsCount();
 }
References getBoughtTicketsCount().
setDate()
void Event::setDate (const Date & date)
сетър на датата
Definition at line 101 of file Event.cpp.
{
     Event::date = date;
 }
References date.
setHall()
void Event::setHall (Hall hall)
сетър на залата
Definition at line 20 of file Event.cpp.
{
     Event::hall = hall;
 }
References hall.
setName()
void Event::setName (const std::string & name)
сетър на името
Definition at line 11 of file Event.cpp.
{
     Event::name = name;
 }
References name.
unbookTicket()
void Event::unbookTicket (int row, int seat)
unbooks a note on given row and seat
метод за премахване на запазен билет
Definition at line 68 of file Event.cpp.
{
     Hall h = this->getHall();
     int seatToUnBook = ((row -1) * h.getSeats()) + (seat-1);
     this->seats[seatToUnBook] =-1;
     this->notes.erase(std::make_pair(row,seat));  //delete old note
 }
References getHall(), Hall::getSeats(), notes, and seats.
Member Data Documentation
date
Date Event::date private
пази датата на събитието
Definition at line 20 of file Event.h.
hall
Hall Event::hall private
пази залата на събитието
Definition at line 21 of file Event.h.
name
std::string Event::name private
пази името на събитието
Definition at line 19 of file Event.h.
notes
std::map<std::pair<int, int>, std::string> Event::notes private
пази бележките на събитието
Definition at line 23 of file Event.h.
seats
std::vector<int> Event::seats private
пази местата на събитието
Definition at line 22 of file Event.h.
The documentation for this class was generated from the following files:
C:/Users/Moni/CLionProjects/Tickets/headers/Event.h
C:/Users/Moni/CLionProjects/Tickets/sources/Event.cpp