Tickets: Date Class Reference
Date Class Reference
Клас който дефинира датата
#include <Date.h>
Public Member Functions
Date ()
Date (int day, int month, int year)
int getDay () const
void setDay (int day)
int getMonth () const
void setMonth (int month)
int getYear () const
void setYear (int year)
bool operator< (const Date &other) const
Returns if given date is earlier.
bool operator<= (const Date &other) const
bool operator== (const Date &other) const
Returns bool if two dates are the same.
bool isLeapYear () const
Returns if the year is leap.
Private Attributes
int day
int month
int year
Detailed Description
Клас който дефинира датата
Definition at line 12 of file Date.h.
Constructor & Destructor Documentation
Date() [1/2]
Date::Date ()
Definition at line 124 of file Date.cpp.
            {
 }
Date() [2/2]
Date::Date (int day, int month, int year)
Definition at line 9 of file Date.cpp.
{
     setYear(year);
     setMonth(month);
     setDay(day);
 }
References day, month, setDay(), setMonth(), setYear(), and year.
Member Function Documentation
getDay()
int Date::getDay () const
Definition at line 15 of file Date.cpp.
{
     return day;
 }
References day.
getMonth()
int Date::getMonth () const
Definition at line 45 of file Date.cpp.
{
     return month;
 }
References month.
getYear()
int Date::getYear () const
Definition at line 58 of file Date.cpp.
{
     return year;
 }
References year.
isLeapYear()
bool Date::isLeapYear () const
Returns if the year is leap.
Definition at line 110 of file Date.cpp.
{
     if (this->getYear() % 4 == 0)
     {
         if (this->getYear() % 100 == 0)
         {
             return this->getYear() % 400 == 0;
         }
         else
             return true;
     }
     else
         return false;
 }
References getYear().
operator<()
bool Date::operator< (const Date & other) const
Returns if given date is earlier.
Definition at line 67 of file Date.cpp.
{
     if(this->getYear() < other.getYear()){
         return true;
     }
     else if(this->getYear() == other.getYear()){
         if(this->getMonth()< other.getMonth()){
             return true;
         }
         else if(this->getMonth() == other.getMonth()){
             return this->getDay() < other.getDay();
         }
         else{
             return false;
         }
     }
     else{
         return false;
     }
 }
References getDay(), getMonth(), and getYear().
operator<=()
bool Date::operator<= (const Date & other) const
Definition at line 87 of file Date.cpp.
{
     if(this->getYear() < other.getYear()){
         return true;
     }
     else if(this->getYear() == other.getYear()){
         if(this->getMonth()< other.getMonth()){
             return true;
         }
         else if(this->getMonth() == other.getMonth()){
             if(this->getDay() == other.getDay()){
                 return true;
             }
             return this->getDay() <= other.getDay();
         }
         else{
             return false;
         }
     }
     else{
         return false;
     }
 }
References getDay(), getMonth(), and getYear().
operator==()
bool Date::operator== (const Date & other) const
Returns bool if two dates are the same.
Definition at line 128 of file Date.cpp.
{
     return this->getYear() == other.getYear()
            && this->getMonth() == other.getMonth()
            && this->getDay() == other.getDay();
 }
References getDay(), getMonth(), and getYear().
setDay()
void Date::setDay (int day)
Definition at line 19 of file Date.cpp.
{
     if(this->getMonth() == 2){
         if(day == 29 && isLeapYear()){
             this->day = day;
         }
         else if(day == 29){
             throw std::invalid_argument( "invalid day" );
         }
         else if(day>=1 && day<29){
             this->day = day;
         }
     }
     else if(this->getMonth()>=1 && this->getMonth()<=12){
         int monthDays = monthsLenght[this->getMonth()];
         if(day >= 1 && day<=monthDays){
             this->day = day;
         }
         else{
             throw std::invalid_argument( "invalid day" );
         }
     }
     else{
         throw std::invalid_argument( "invalid day" );
     }
 }
References day, getMonth(), isLeapYear(), and monthsLenght.
setMonth()
void Date::setMonth (int month)
Definition at line 49 of file Date.cpp.
{
     if(month>=1 && month<=12){
         Date::month = month;
     }
     else{
     throw std::invalid_argument( "invalid month" );
     }
 }
References month.
setYear()
void Date::setYear (int year)
Definition at line 62 of file Date.cpp.
{
     Date::year = year;
 }
References year.
Member Data Documentation
day
int Date::day private
Definition at line 14 of file Date.h.
month
int Date::month private
Definition at line 14 of file Date.h.
year
int Date::year private
Definition at line 14 of file Date.h.
The documentation for this class was generated from the following files:
C:/Users/Moni/CLionProjects/Tickets/headers/Date.h
C:/Users/Moni/CLionProjects/Tickets/sources/Date.cpp