Tickets: Ticket Class Reference
Ticket Class Reference
Клас който дефинира билет
#include <Ticket.h>
Public Member Functions
Ticket ()
Ticket (const std::string &name, int row, int seat, const Date &date, const std::string &note, const std::string &hall)
Ticket (const std::string &name, int row, int seat, const Date &date, const std::string &note)
std::string getId () const
void setId (const std::string &id)
const std::string & getName () const
void setName (const std::string &name)
int getRow () const
void setRow (int row)
int getSeat () const
void setSeat (int seat)
int getYear () const
void setYear (int year)
int getMonth () const
void setMonth (int month)
int getDay () const
void setDay (int day)
const std::string & getHashedId () const
void setHashedId (const std::string &hashedId)
std::string hashIt (int row, int seat, const std::string &name)
bool isBought () const
void setBought (bool bought)
const std::string & getNote () const
void setNote (const std::string &note)
const std::string & getHall () const
void setHall (const std::string &hall)
const Date & getDate () const
void setDate (const Date &date)
Private Attributes
std::string hashedId
std::string name
std::string note
std::string hall
int row
int seat
Date date
bool bought
Detailed Description
Клас който дефинира билет
Definition at line 16 of file Ticket.h.
Constructor & Destructor Documentation
Ticket() [1/3]
Ticket::Ticket ()
Definition at line 45 of file Ticket.cpp.
                {
 }
Ticket() [2/3]
Ticket::Ticket (const std::string & name, int row, int seat, const Date & date, const std::string & note, const std::string & hall)
Definition at line 78 of file Ticket.cpp.
{
     this->setHall(hall);
     Ticket(name,row,seat,date,note);
 }
References date, name, note, row, seat, setHall(), and Ticket().
Ticket() [3/3]
Ticket::Ticket (const std::string & name, int row, int seat, const Date & date, const std::string & note)
Definition at line 48 of file Ticket.cpp.
{
     this->setName(name);
     this->setNote(note);
     this->setRow(row);
     this->setDate(date);
     this->setSeat(seat);
     this->setBought(false);
     // 4 random numbers + row + 2 random numbers + seat + 4 random
     std::string hash = "";
     for (int i = 0; i < 4; i++) {
         int randomNumber = rand() % 10;
         hash += std::to_string(randomNumber);
     }
     hash += std::to_string(row);
     for (int i = 0; i < 2; i++) {
         int randomNumber = rand() % 10;
         hash += std::to_string(randomNumber);
     }
     hash += std::to_string(seat );
     for (int i = 0; i < 4; i++) {
         int randomNumber = rand() % 10;
         hash += std::to_string(randomNumber);
     }
     this->setHashedId(hash);
 }
References row, seat, setBought(), setDate(), setHashedId(), setName(), setNote(), setRow(), and setSeat().
Member Function Documentation
getDate()
const Date & Ticket::getDate () const
Definition at line 122 of file Ticket.cpp.
{
     return date;
 }
References date.
getDay()
int Ticket::getDay () const
Definition at line 41 of file Ticket.cpp.
{
     return this->date.getDay();
 }
References date, and Date::getDay().
getHall()
const std::string & Ticket::getHall () const
Definition at line 114 of file Ticket.cpp.
{
     return hall;
 }
References hall.
getHashedId()
const std::string & Ticket::getHashedId () const
Definition at line 83 of file Ticket.cpp.
{
     return this->hashedId;
 }
References hashedId.
getId()
std::string Ticket::getId () const
Definition at line 99 of file Ticket.cpp.
{
     return this->hashedId;
 }
References hashedId.
getMonth()
int Ticket::getMonth () const
Definition at line 37 of file Ticket.cpp.
{
     return this->date.getMonth();
 }
References date, and Date::getMonth().
getName()
const std::string & Ticket::getName () const
Definition at line 9 of file Ticket.cpp.
{
     return name;
 }
References name.
getNote()
const std::string & Ticket::getNote () const
Definition at line 106 of file Ticket.cpp.
{
     return note;
 }
References note.
getRow()
int Ticket::getRow () const
Definition at line 17 of file Ticket.cpp.
{
     return row;
 }
References row.
getSeat()
int Ticket::getSeat () const
Definition at line 25 of file Ticket.cpp.
{
     return seat;
 }
References seat.
getYear()
int Ticket::getYear () const
Definition at line 33 of file Ticket.cpp.
{
     return this->date.getYear();
 }
References date, and Date::getYear().
hashIt()
std::string Ticket::hashIt (int row, int seat, const std::string & name)
isBought()
bool Ticket::isBought () const
Definition at line 91 of file Ticket.cpp.
{
     return bought;
 }
References bought.
setBought()
void Ticket::setBought (bool bought)
Definition at line 95 of file Ticket.cpp.
{
     Ticket::bought = bought;
 }
References bought.
setDate()
void Ticket::setDate (const Date & date)
Definition at line 126 of file Ticket.cpp.
{
     Ticket::date = date;
 }
References date.
setDay()
void Ticket::setDay (int day)
setHall()
void Ticket::setHall (const std::string & hall)
Definition at line 118 of file Ticket.cpp.
{
     Ticket::hall = hall;
 }
References hall.
setHashedId()
void Ticket::setHashedId (const std::string & hashedId)
Definition at line 87 of file Ticket.cpp.
{
     Ticket::hashedId = hashedId;
 }
References hashedId.
setId()
void Ticket::setId (const std::string & id)
Definition at line 102 of file Ticket.cpp.
{
     this->hashedId = id;
 }
References hashedId.
setMonth()
void Ticket::setMonth (int month)
setName()
void Ticket::setName (const std::string & name)
Definition at line 13 of file Ticket.cpp.
{
     Ticket::name = name;
 }
References name.
setNote()
void Ticket::setNote (const std::string & note)
Definition at line 110 of file Ticket.cpp.
{
     Ticket::note = note;
 }
References note.
setRow()
void Ticket::setRow (int row)
Definition at line 21 of file Ticket.cpp.
{
     Ticket::row = row;
 }
References row.
setSeat()
void Ticket::setSeat (int seat)
Definition at line 29 of file Ticket.cpp.
{
     Ticket::seat = seat;
 }
References seat.
setYear()
void Ticket::setYear (int year)
Member Data Documentation
bought
bool Ticket::bought private
Definition at line 25 of file Ticket.h.
date
Date Ticket::date private
Definition at line 24 of file Ticket.h.
hall
std::string Ticket::hall private
Definition at line 21 of file Ticket.h.
hashedId
std::string Ticket::hashedId private
Definition at line 18 of file Ticket.h.
name
std::string Ticket::name private
Definition at line 19 of file Ticket.h.
note
std::string Ticket::note private
Definition at line 20 of file Ticket.h.
row
int Ticket::row private
Definition at line 22 of file Ticket.h.
seat
int Ticket::seat private
Definition at line 23 of file Ticket.h.
The documentation for this class was generated from the following files:
C:/Users/Moni/CLionProjects/Tickets/headers/Ticket.h
C:/Users/Moni/CLionProjects/Tickets/sources/Ticket.cpp