Tickets: TicketArr Class Reference
TicketArr Class Reference
Клас който дефинира списък от билети
#include <TicketArr.h>
Public Member Functions
int getSize ()
const std::vector< Ticket > & getTickets () const
TicketArr & addTicket (const Ticket &newTicket)
adds a ticket in the ticket array
void removeTicketWithSeatNumberAndName (const std::string &name, int row, int seat, const Date &date)
removes a ticket by given seat and date from the ticket array
Ticket * getTicketWithID (const std::string &id)
returns a ticket by given id
void addHashedId (const Ticket &ticket)
void unbookTicket (const std::string &name, int row, int seat, const Date &date)
unbooks a ticket by given name, seat and date
void buyTicket (const std::string &name, int row, int seat, const Date &date)
buys a ticket by given name, seat and date
void printHallTickets (const Date &startDate, const Date &endDate, Hall *hall, EventArr *eventArr)
print halls tickets by given date range and hall
void printHallTickets (const Date &startDate, const Date &endDate, EventArr *eventArr)
print halls tickets by given date range
void getBookedTicketsWithHallName (const Date &date, Hall *hall, HallArr *halls)
Private Attributes
std::vector< Ticket > tickets
Detailed Description
Клас който дефинира списък от билети
Definition at line 17 of file TicketArr.h.
Member Function Documentation
addHashedId()
void TicketArr::addHashedId (const Ticket & ticket)
Definition at line 22 of file TicketArr.cpp.
{
 }
addTicket()
TicketArr & TicketArr::addTicket (const Ticket & newTicket)
adds a ticket in the ticket array
Definition at line 17 of file TicketArr.cpp.
{
     this->tickets.push_back(newTicket);
     return *this;
 }
References tickets.
buyTicket()
void TicketArr::buyTicket (const std::string & name, int row, int seat, const Date & date)
buys a ticket by given name, seat and date
Definition at line 76 of file TicketArr.cpp.
{
     for(int i=0;i< this->getSize();i++){
         Ticket t = this->getTickets()[i];
         if(t.getName() == name
             && t.getDate() == date
            && t.getSeat() == seat
            && t.getRow() == row){
             Ticket *ticketToChange = getTicketWithID(t.getId());
             ticketToChange->setBought(true);
             return;
         }
     }
 }
References Ticket::getDate(), Ticket::getId(), Ticket::getName(), Ticket::getRow(), Ticket::getSeat(), getSize(), getTickets(), getTicketWithID(), and Ticket::setBought().
getBookedTicketsWithHallName()
void TicketArr::getBookedTicketsWithHallName (const Date & date, Hall * hall, HallArr * halls)
getSize()
int TicketArr::getSize ()
Definition at line 12 of file TicketArr.cpp.
{
     return this->getTickets().size();
 }
References getTickets().
getTickets()
const std::vector< Ticket > & TicketArr::getTickets () const
Definition at line 8 of file TicketArr.cpp.
{
     return tickets;
 }
References tickets.
getTicketWithID()
Ticket * TicketArr::getTicketWithID (const std::string & id)
returns a ticket by given id
Definition at line 27 of file TicketArr.cpp.
{
     for(int i=0;i<this->getSize();i++){
         Ticket t = this->tickets[i];
         if(t.getId() == id){
             return &this->tickets[i];
         }
     }
     return nullptr;
 }
References Ticket::getId(), getSize(), and tickets.
printHallTickets() [1/2]
void TicketArr::printHallTickets (const Date & startDate, const Date & endDate, EventArr * eventArr)
print halls tickets by given date range
Definition at line 107 of file TicketArr.cpp.
{
     long eventsTicketsSum =0;
     for(int i=0;i<eventArr->getSize();i++){
         Event event = eventArr->getEvents()[i];
         if(event.getDate()<=endDate && startDate<=event.getDate()){
             std::cout<<"Event: "+event.getName()<<", Tickets bought: "<< event.getBoughtTicketsCount()<<std::endl;
             eventsTicketsSum += event.getBoughtTicketsCount();
         }
     }
     std::cout<<"Total tickets: "<<eventsTicketsSum<<std::endl;
 }
References EventArr::getEvents(), and EventArr::getSize().
printHallTickets() [2/2]
void TicketArr::printHallTickets (const Date & startDate, const Date & endDate, Hall * hall, EventArr * eventArr)
print halls tickets by given date range and hall
Definition at line 91 of file TicketArr.cpp.
{
   long eventsTicketsSum =0;
    for(int i=0;i<eventArr->getSize();i++){
        Event event = eventArr->getEvents()[i];
        if(event.getDate()<=endDate && startDate<=event.getDate() && event.getHall().getId() == hall->getId()){
            std::cout<<"Event: "+event.getName()<<", Tickets bought: "<< event.getBoughtTicketsCount()<<std::endl;
            eventsTicketsSum += event.getBoughtTicketsCount();
        }
     }
     std::cout<<"Total tickets: "<<eventsTicketsSum<<std::endl;
 }
References EventArr::getEvents(), Hall::getId(), and EventArr::getSize().
removeTicketWithSeatNumberAndName()
void TicketArr::removeTicketWithSeatNumberAndName (const std::string & name, int row, int seat, const Date & date)
removes a ticket by given seat and date from the ticket array
Definition at line 39 of file TicketArr.cpp.
{
     for(int i=0;i< this->getSize();i++){
         Ticket t = this->getTickets()[i];
         if(t.getName() == name
         && t.getDate() == date
         && t.getSeat() == seat
         && t.getRow() == row){
             this->tickets.erase(this->tickets.begin()+i);
             return;
         }
     }
     throw std::invalid_argument("Ticket not found!");
 }
References Ticket::getDate(), Ticket::getName(), Ticket::getRow(), Ticket::getSeat(), getSize(), getTickets(), and tickets.
unbookTicket()
void TicketArr::unbookTicket (const std::string & name, int row, int seat, const Date & date)
unbooks a ticket by given name, seat and date
Definition at line 54 of file TicketArr.cpp.
{
     std::string hash = "";
     for (int i = 0; i < 4; i++) {
         int randomNumber = rand() % 10;
         hash += std::to_string(randomNumber);
     }
     hash += std::to_string(row);
     for (int i = 0; i < 2; i++) {
         int randomNumber = rand() % 10;
         hash += std::to_string(randomNumber);
     }
     hash += std::to_string(seat + 1);
     for (int i = 0; i < 4; i++) {
         int randomNumber = rand() % 10;
         hash += std::to_string(randomNumber);
     }
     removeTicketWithSeatNumberAndName(name,row,seat,date);
 }
References removeTicketWithSeatNumberAndName().
Member Data Documentation
tickets
std::vector<Ticket> TicketArr::tickets private
Definition at line 19 of file TicketArr.h.
The documentation for this class was generated from the following files:
C:/Users/Moni/CLionProjects/Tickets/headers/TicketArr.h
C:/Users/Moni/CLionProjects/Tickets/sources/TicketArr.cpp